name: AbsoluteWelcome
version: 2.1
main: tk.absolutesgamers.welcome.Welcome
author: Absolute
description: Add a Welcome Message on the server!

commands:
  welcome:
    usage: /<command> or /<command> set
    description: Change or show the Welcome Message!

permission:
  welcome.see:
    default: op
    description: Allow the player see the Welcome Message!
  welcome.set:
    default: op
    description: Allow the player change the Welcome Message!
